quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=molina_test
quarkus.datasource.password=Morales1610*
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/catalogo_test

quarkus.hibernate-orm.log.sql=true

smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=https://molina-catalogo.com

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.headers=origin, content-type, accept, authorization, x-requested-with
quarkus.http.cors.methods=GET, POST, PUT, DELETE, OPTIONS, HEAD