quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=molina_test
quarkus.datasource.password=Morales1610*
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/catalogo_test

quarkus.hibernate-orm.log.sql=true